In [36]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg  

In [19]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
b = np.array([12, 2, 1])
np.linalg.solve(a,b)
#  Задание 6.1

array([-9.2       ,  0.9       ,  6.46666667])

In [21]:
a = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
b = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(a,b)
#  Задание 6.2

<ipython-input-21-92192c7bfdbb>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(a,b)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [23]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)
# Задание 6.3 Не имеет решения

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

In [34]:
A = np.array([[1, 2, 3], [1, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A,B)
# Задание 6.3 с изменением

array([  1.5       , -20.5       ,  17.16666667])

In [42]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
print(np.dot(P.transpose(), A) - np.dot(L, U))

C = np.dot(L, U)
P, L, U = scipy.linalg.lu(A)

print("det A = ", np.linalg.det(A))
print("P = ", P)
print("L = ", L)
print("U = ", U)

B = np.array([4, 1, 7, 3])   # вот тут не понял, что это в примере было
np.linalg.solve(C, B)

# Задание 6.4. В jupyter выдает ошибку (даже если скопировать из методички код) в PyCharm все нормально считает.


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
det A =  432.00000000000017
P =  [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L =  [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U =  [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 4 is different from 3)

In [48]:
a = np.array([[1, 2, -1], [8, -5, 2]])
b = np.array([1, 12])
np.linalg.lstsq(a,b)
# Задание 6.5

<ipython-input-48-18e534a98de6>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(a,b)


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

In [56]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)
R1 = R[:2, :2]
B1 = np.dot(np.transpose(Q), B)[:2]
X1 = np.linalg.solve(R1, B1)
X1
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)
# Задание 6.6

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
[1.50000000e+00 3.92767275e-15 0.00000000e+00]


1.499999999999996