# Матрицы и матричные операции

In [1]:
import numpy as np

### Задание 1

Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ; произведения матриц не определены, посчитать произведение нельзя, т.к. количество столбцов в A не совпадает с количеством строк в B;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;  произведения матриц не определены, A * B будет матрица 2 * 3, B * A нельзя перемножить;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ; произведения определены, A  * B получится матрица 8 *  8 (квадратная), B * A получится матрица 3 * 3 (квадратная);

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 ; произведения определены, A  * B и B * A получатся две матрицы 4 * 4.

### Задание 2

Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [30]:
a = np.array([[1,-2], [3,0]])
b = np.array([[4,-1], [0,5]])

Сумма:

$A + B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

In [28]:
a + b

array([[ 5, -3],
       [ 3,  5]])

Произведение:

$A * B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ * $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1*4 - 2 * 0 & 1 * -1 - 2 * 5\\ 
3 * 4 + 0 * 0 & 3 * -1 + 0 * -5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [26]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

$B * A = \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ * $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ = $\begin{pmatrix}
4 * 1 - 1 * 3 & 4 * - 2 - 1 * 0\\ 
0 * 1 + 5 * 3 & 0 * - 2 + 5 * 0
\end{pmatrix}$ = $\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [31]:
np.dot(b, a)

array([[ 1, -8],
       [15,  0]])

### Задание 3

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A - 2B + 4C =\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ - $\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$ + $\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$ = $\begin{pmatrix}
11 & 15\\ 
17 & -16
\end{pmatrix}$

In [32]:
a = np.array([[1,7], [3,-6]])
b = np.array([[0,5], [2,-1]])
c = np.array([[2,-4], [1,1]])

In [36]:
3 * a + 2 * b + 4 * c

array([[ 11,  15],
       [ 17, -16]])

### Задание 4

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$
$A^T = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$

$A^T = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$
$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$

$A * A^T = \begin{pmatrix}
4 * 4 + 1 * 1 & 4 * 5 + 1 * -2 & 4 * 2 + 1 * 3\\ 
5 * 4 - 2 * 1 & 5 * 5 + (- 2) * - 2 & 5 * 2 - 2 * 3\\
2 * 4 + 3 * 1 & 2 * 5 + 3 * -2 & 2 * 2 + 3 * 3\\ 
\end{pmatrix}$ = $\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$

$A^T * A = \begin{pmatrix}
4 * 4 + 5 * 5 + 2 * 2 & 4 * 1 + 5 * -2 + 2 * 3\\ 
1 * 4 - 2 * 5 + 3 * 2 & 1 * 1 + (- 2) * - 2 + 3 * 3\\
\end{pmatrix}$ = $\begin{pmatrix}
45 & 0\\ 
0 & 14\\
\end{pmatrix}$

In [42]:
a = np.array([[4,1], [5,-2], [2,3]])
a.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [44]:
np.dot(a,a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [45]:
np.dot(a.T,a)

array([[45,  0],
       [ 0, 14]])

### ПЗ 2

### Задание 1

Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


а) $sin^2x + cos^2x = 1$

б) 4 * 5 * 9 = 180

в) 1 * (5 * 9 - 8 * 6) - 2 * (4 * 9 - 7 * 6) + 3 * (4 * 8 - 7 * 5) = 0

### Задание 2

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$; Ответ: 16
    
   б) $det(A^{T})$; Ответ: 4
    
   в) $det(2A)$. Ответ: 8

### Задание 3

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [73]:
a1 = np.array([[-2,7,-3], [4,-14,6], [-3,7,13]])
np.linalg.det(a1)

0.0

Ответ: определитель равен 0, матрица является вырожденной.

### Задание 4

Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [75]:
a2 = np.array([[1,2,3],[1,1,1],[2,3,4]])
b2 = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])

Ранг матрицы а):

In [78]:
np.linalg.matrix_rank(a2)

2

Ранг матрицы б):

In [79]:
np.linalg.matrix_rank(b2)

3