# Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

In [88]:
import numpy as np
import pandas as pd

### Задание 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy.
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [89]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

Смещенная ковариация:

In [111]:
cov_sm_1 = (np.mean(zp*ks)-np.mean(zp)*np.mean(ks))
cov_sm_1

9157.839999999997

In [112]:
cov_sm_1 = np.cov(zp,ks,ddof=0)
cov_sm_1

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Несмещенная ковариация:

In [113]:
cov_nsme_1 = sum((ks-np.mean(ks))*(zp-np.mean(zp)))/9
cov_nsme_1

10175.377777777778

In [114]:
cov_nsme_1 = np.cov(zp,ks,ddof=1)
cov_nsme_1

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

Смещенное квадратичное отклонение:

In [115]:
zp_std = np.std(zp)
zp_std

59.115480206118605

In [116]:
ks_std = np.std(ks)
ks_std

174.55340157098058

Несмещенное квадратичное отклонение:

In [117]:
zp_std_ns = np.std(zp,ddof=1)
zp_std_ns

62.31318747531162

In [118]:
ks_std_ns = np.std(ks,ddof=1)
ks_std_ns

183.99544076477068

Корреляция со смещенной cov и $\sigma$:

In [119]:
r = cov_sm_1/(zp_std*ks_std)
r

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

Numpy

In [120]:
np.corrcoef(ks,zp)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Pandas

In [121]:
pd.DataFrame({'ks':ks, 'zp': zp}).corr()

ks       zp
ks  1.00000  0.88749
zp  0.88749  1.00000

Корреляция с несмещенной cov и $\sigma$:

In [122]:
r = cov_nsme_1/(zp_std_ns*ks_std_ns)
r

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

Почему одинаковые ответы получаются, с использованием несмещенных и смещенных ковариаций и сигм???

Как получается эта разниц, если квадратичное отклонение делать не смещенным, смещенным и в corrcoef ddof 1 прописать, результат не меняется из-за ошибки?

Пример:

In [123]:
zp_s = np.std(zp,ddof=1)
zp_s

62.31318747531162

In [124]:
ks_s = np.std(ks,ddof=1)
ks_s

183.99544076477068

In [128]:
r_ = cov_nsme_1/(zp_s*ks_s)
r_

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [129]:
np.corrcoef(ks,zp)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [130]:
np.corrcoef(ks,zp,ddof=1)

/Users/h/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: bias and ddof have no effect and are deprecated
  """Entry point for launching an IPython kernel.


array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

# -------------------------------------------------------------------------------------------

### Задание 2

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [132]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [133]:
t = 2.262

In [134]:
iq_mean = np.mean(iq)
iq_mean

118.1

In [135]:
std_iq = np.std(iq,ddof=1)
std_iq

10.54566788359614

In [139]:
iq_mean + (t * std_iq / np.sqrt(len(iq)))

125.64339223691834

In [141]:
iq_mean - (t * std_iq / np.sqrt(len(iq)))

110.55660776308164

Доверительный интервал для математического ожидания с надежностью 0.95 [110.56,125.64]

### Задание 3

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [142]:
d = 25
n = 27
x = 172.4
a = 0.05
std = np.sqrt(d)

In [143]:
z = 1.96

In [144]:
x+(z*std/np.sqrt(n))

174.28601087935277

In [147]:
x-(z*std/np.sqrt(n))

170.51398912064724

Доверительный интервал для математического ожидания с надежностью 0.95 [170.51,174.29]

С проектом еще определяюсь!!!